name: Windows build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up vcpkg and dependencies
        uses: lukka/run-vcpkg@v11
        with:
          runVcpkgInstall: true
      - name: Configure
        shell: pwsh
        run: cmake -S . -B build/windows -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake"
      - name: Build
        run: cmake --build build/windows
